ProductMart.PL/Controllers/ProductsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProductCatalog.BLL.Interfaces;
using ProductCatalog.DAL.Models;
using ProductCatalog.PL.ViewModels;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ProductCatalog.PL.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ProductsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        public ProductsController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork= unitOfWork;
            _mapper= mapper;
        }
        public async Task<IActionResult> Index(string SearchValue)
        {
            if(int.TryParse(SearchValue, out int searchIntValue))
            {
                var products = _unitOfWork.ProductsRepository.SearchProductsByCategory(searchIntValue);
                var mappedProduct = _mapper.Map<IEnumerable<Products>, IEnumerable<ProductsViewModel>>(products);
                return View(mappedProduct);
            }
            else
            {
                var products = await _unitOfWork.ProductsRepository.GetAll();
                var mappedProduct = _mapper.Map<IEnumerable<Products>, IEnumerable<ProductsViewModel>>(products);
                return View(mappedProduct);

            }
            }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Products products)
        {
            if (ModelState.IsValid)
            {
                await _unitOfWork.ProductsRepository.Add(products);
                await _unitOfWork.Complete();
                return RedirectToAction("Index");
            }

            return View();
        }
        public async Task<IActionResult> Details(int? id, string viewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var product = await _unitOfWork.ProductsRepository.Get(id.Value);
            if (product == null)
                return NotFound();
            var mappedProduct = _mapper.Map<Products,ProductsViewModel>(product);

            return View(viewName, mappedProduct);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            return await Details(id, "Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] int id, ProductsViewModel ProductVM)

        {
            if (id != ProductVM.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var mappedProduct = _mapper.Map<ProductsViewModel, Products>(ProductVM);
                    _unitOfWork.ProductsRepository.Update(mappedProduct);
                    await _unitOfWork.Complete();
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(string.Empty, ex.Message);
                }

            }

            return View(ProductVM);
        }
        public async Task<IActionResult> Delete(int? id)
        {

            return await Details(id, "Delete");
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id, ProductsViewModel ProductsVM)
        {
            if (id != ProductsVM.Id)
                return BadRequest();
            try
            {
                var mappedProducts = _mapper.Map<ProductsViewModel, Products>(ProductsVM);
                _unitOfWork.ProductsRepository.Delete(mappedProducts);
                await _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(ProductsVM);
            }
        }
    }
}

ProductMart.PL/Controllers/UserProductsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProductCatalog.BLL.Interfaces;
using ProductCatalog.DAL.Models;
using ProductCatalog.PL.ViewModels;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ProductCatalog.PL.Controllers
{
    public class UserProductsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        public UserProductsController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(string SearchValue)
        {
            var dproducts = await _unitOfWork.ProductsRepository.GetAll();
            var duration = _unitOfWork.ProductsRepository.CompareDuration(dproducts);
            if(duration is not null) { 
            if (int.TryParse(SearchValue, out int searchIntValue))
            {
                var products = _unitOfWork.ProductsRepository.SearchProductsByCategory(searchIntValue);
                var mappedProduct = _mapper.Map<IEnumerable<Products>, IEnumerable<ProductsViewModel>>(products);
                return View(mappedProduct);
            }
            else
            {
                var products = await _unitOfWork.ProductsRepository.GetAll();
                var mappedProduct = _mapper.Map<IEnumerable<Products>, IEnumerable<ProductsViewModel>>(products);
                return View(mappedProduct);

            }
            }
            else { return View(null); }
        }
        public async Task<IActionResult> Details(int? id, string viewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var product = await _unitOfWork.ProductsRepository.Get(id.Value);
            if (product == null)
                return NotFound();
            var mappedProduct = _mapper.Map<Products, ProductsViewModel>(product);

            return View(viewName, mappedProduct);
        }

    }
}

ProductMart.PL/Views/Shared/_ButtonsPartialView.cshtml
@model string

<td>
    <a asp-action="Details" asp-route-id="@Model" class=" btn btn-warning"><i class="fas fa-eye"></i> Details</a>

</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class=" btn btn-success"><i class="fas fa-edit"></i> Update</a>

</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class=" btn btn-danger">   <i class="fas fa-trash"></i> Delete</a>

</td>

ProductMart.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductMart.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProductMart.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserProducts">UserProducts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products">Admins Only</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProductMart.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("validationScriptSection", required: false)
</body>
</html>